import type { Product, User, ProductCategory, Shop, Complaint } from './types';
import { PlaceHolderImages } from './placeholder-images';

// Initialize shops in localStorage if not already present
export const initializeShopsInStorage = () => {
  if (typeof window !== 'undefined') {
    const storedShops = localStorage.getItem('shops');
    if (!storedShops) {
      // Start with empty shops array - shops will be added through registration
      localStorage.setItem('shops', JSON.stringify([]));
    }
  }
};

// Clear all existing shops from localStorage
export const clearAllShops = () => {
  if (typeof window !== 'undefined') {
    localStorage.setItem('shops', JSON.stringify([]));
    // Dispatch event to notify components of the change
    window.dispatchEvent(new Event('shopStatusChanged'));
  }
};

const findImage = (id: string) => PlaceHolderImages.find(img => img.id === id) || { imageUrl: '', imageHint: '' };

export const mockUser: User = {
  id: 'user-1',
  name: 'Alex Green',
  email: 'alex.green@trustkart.com',
  avatar: findImage('user_avatar_1').imageUrl,
  role: 'shopkeeper',
};

const today = new Date();
const addDays = (date: Date, days: number) => {
  const result = new Date(date);
  result.setDate(result.getDate() + days);
  return result;
};

const subtractDays = (date: Date, days: number) => {
  const result = new Date(date);
  result.setDate(result.getDate() - days);
  return result;
};

export const mockShops: Shop[] = [
    { 
      id: 'shop-1', 
      name: 'Kiran General Store', 
      location: 'Andheri West, Mumbai', 
      address: '123 Link Road, Near Andheri Station',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400058',
      coordinates: { latitude: 19.1197, longitude: 72.8464 },
      imageUrl: 'https://picsum.photos/seed/shop1/600/300', 
      imageHint: 'grocery store',
      ownerId: 'owner-1',
      status: 'approved',
      registrationDate: new Date('2024-01-15'),
      approvalDate: new Date('2024-01-20'),
      documents: [],
      businessType: 'grocery',
      description: 'Fresh vegetables, groceries and daily essentials',
      phone: '+91 98765 43210',
      email: 'kirangeneral@example.com'
    },
    { 
      id: 'shop-2', 
      name: 'Reliance Fresh', 
      location: 'Bandra Kurla Complex, Mumbai', 
      address: '456 BKC Complex, Shop No. 12',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400051',
      coordinates: { latitude: 19.0596, longitude: 72.8647 },
      imageUrl: 'https://picsum.photos/seed/shop2/600/300', 
      imageHint: 'convenience store',
      ownerId: 'owner-2',
      status: 'approved',
      registrationDate: new Date('2024-02-01'),
      approvalDate: new Date('2024-02-05'),
      documents: [],
      businessType: 'convenience',
      description: 'Quick snacks, beverages and ready-to-eat items',
      phone: '+91 98765 43211',
      email: 'reliancefresh@example.com'
    },
    { 
      id: 'shop-3', 
      name: 'Sharma Provision Store', 
      location: 'Powai, Mumbai', 
      address: '789 Powai Lake Road, Near IIT',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400076',
      coordinates: { latitude: 19.1176, longitude: 72.9060 },
      imageUrl: 'https://picsum.photos/seed/shop3/600/300', 
      imageHint: 'local shop',
      ownerId: 'owner-3',
      status: 'approved',
      registrationDate: new Date('2024-01-20'),
      approvalDate: new Date('2024-01-25'),
      documents: [],
      businessType: 'grocery',
      description: 'Local neighborhood store with fresh groceries',
      phone: '+91 98765 43212',
      email: 'sharmaprovision@example.com'
    },
    { 
      id: 'shop-4', 
      name: 'Big Bazaar', 
      location: 'Phoenix MarketCity, Kurla', 
      address: '321 Phoenix MarketCity, Ground Floor',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400070',
      coordinates: { latitude: 19.0884, longitude: 72.8840 },
      imageUrl: 'https://picsum.photos/seed/shop4/600/300', 
      imageHint: 'supermarket aisle',
      ownerId: 'owner-4',
      status: 'approved',
      registrationDate: new Date('2024-02-10'),
      approvalDate: new Date('2024-02-15'),
      documents: [],
      businessType: 'supermarket',
      description: 'Large supermarket with wide variety of products',
      phone: '+91 98765 43213',
      email: 'bigbazaar@example.com'
    },
    // Add a pending shop for testing
    { 
      id: 'shop-5', 
      name: 'Patel Kirana Store', 
      location: 'Goregaon East, Mumbai', 
      address: '555 Goregaon East, Near Station',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400063',
      coordinates: { latitude: 19.1550, longitude: 72.8497 },
      imageUrl: 'https://picsum.photos/seed/shop5/600/300', 
      imageHint: 'new shop',
      ownerId: 'owner-5',
      status: 'pending',
      registrationDate: new Date('2024-03-01'),
      documents: [],
      businessType: 'grocery',
      description: 'Newly registered kirana store awaiting approval',
      phone: '+91 98765 43214',
      email: 'patelkirana@example.com'
    },
    // Add Kala Store for demo
    { 
      id: 'shop-kala', 
      name: 'Kala Store', 
      location: 'Commercial Street, Mumbai', 
      address: '789 Commercial Street, Near Market',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      coordinates: { latitude: 19.0176, longitude: 72.8562 },
      imageUrl: 'https://picsum.photos/seed/kala-shop/600/200', 
      imageHint: 'kala store',
      ownerId: 'shopkeeper-kala',
      status: 'approved',
      registrationDate: new Date('2024-01-01'),
      approvalDate: new Date('2024-01-02'),
      documents: [],
      businessType: 'grocery',
      description: 'Premium grocery store with fresh vegetables and daily essentials',
      phone: '+91 98765 43215',
      email: 'kala@shopkeeper.com',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-02')
    },
];


export const mockCategories: ProductCategory[] = [
  { id: 'cat-2', name: 'Dairy, Bread & Eggs', imageUrl: 'https://picsum.photos/seed/dairy_cat/100/100', imageHint: 'milk bread' },
  { id: 'cat-3', name: 'Fruits & Vegetables', imageUrl: 'https://picsum.photos/seed/produce_cat/100/100', imageHint: 'fresh vegetables' },
  { id: 'cat-4', name: 'Cold Drinks & Juices', imageUrl: 'https://picsum.photos/seed/drinks_cat/100/100', imageHint: 'soda bottle' },
  { id: 'cat-5', name: 'Snacks & Munchies', imageUrl: 'https://picsum.photos/seed/snacks_cat/100/100', imageHint: 'potato chips' },
  { id: 'cat-6', name: 'Breakfast & Instant Food', imageUrl: 'https://picsum.photos/seed/breakfast_cat/100/100', imageHint: 'cereal bowl' },
  { id: 'cat-7', name: 'Sweet Tooth', imageUrl: 'https://picsum.photos/seed/sweets_cat/100/100', imageHint: 'chocolate bar' },
  { id: 'cat-8', name: 'Bakery & Biscuits', imageUrl: 'https://picsum.photos/seed/bakery_cat/100/100', imageHint: 'cookies biscuits' },
  { id: 'cat-9', name: 'Tea, Coffee & More', imageUrl: 'https://picsum.photos/seed/tea_cat/100/100', imageHint: 'tea cup' },
  { id: 'cat-10', name: 'Masala, Oil & More', imageUrl: 'https://picsum.photos/seed/masala_cat/100/100', imageHint: 'spices masala' },
];

export const mockProducts: Product[] = [
  // Dairy, Bread & Eggs
  {
    id: 'prod-1',
    name: 'Amul Taaza Toned Milk',
    category: 'Dairy, Bread & Eggs',
    categoryId: 'cat-2',
    price: 3.5,
    unit: '1L',
    stockQty: 500,
    sku: 'DAIRY-OM-001',
    imageUrl: 'https://picsum.photos/seed/milk/200/200',
    imageHint: 'milk carton',
    expiryDate: addDays(today, 2), // Expires soon - red indicator
    mfgDate: subtractDays(addDays(today, 2), 8),
    daysUntilExpiry: 2,
    averageDailySales: 10,
    shopId: 'shop-1',
    description: "Amul Taaza Toned Milk is a high-quality, pasteurized milk that is perfect for your daily needs. It's a healthy and nutritious choice for the whole family.",
    inStock: true,
    nutritionalInfo: { calories: '60kcal', protein: '3.5g', carbohydrates: '4.5g', fat: '3.1g' }
  },
  {
    id: 'prod-2',
    name: 'Britannia Brown Bread',
    category: 'Dairy, Bread & Eggs',
    categoryId: 'cat-2',
    price: 5.0,
    unit: '400g',
    stockQty: 350,
    sku: 'BAKERY-SB-002',
    imageUrl: 'https://picsum.photos/seed/bread/200/200',
    imageHint: 'sliced bread',
    expiryDate: addDays(today, 5), // Expires in a week - yellow indicator
    mfgDate: subtractDays(addDays(today, 5), 3),
    daysUntilExpiry: 5,
    averageDailySales: 8,
    shopId: 'shop-1',
    description: "Made from whole wheat flour, Britannia Brown Bread is a healthy and delicious option for your breakfast. It's packed with fibre and nutrients.",
    inStock: true,
    nutritionalInfo: { calories: '250kcal', protein: '9g', carbohydrates: '49g', fat: '3.2g' }
  },
  {
    id: 'prod-3',
    name: 'Free-Range Eggs (12 pack)',
    category: 'Dairy, Bread & Eggs',
    categoryId: 'cat-2',
    price: 4.2,
    unit: '12 pieces',
    stockQty: 12,
    sku: 'DAIRY-EG-003',
    imageUrl: 'https://picsum.photos/seed/eggs/200/200',
    imageHint: 'egg carton',
    expiryDate: addDays(today, 15), // Fresh - green indicator
    mfgDate: subtractDays(addDays(today, 15), 5),
    daysUntilExpiry: 15,
    averageDailySales: 15,
    shopId: 'shop-2',
    description: "Our free-range eggs come from hens that are free to roam and forage. They are a great source of protein and essential vitamins.",
    inStock: true,
    nutritionalInfo: { calories: '78kcal', protein: '6g', carbohydrates: '0.6g', fat: '5g' }
  },
  {
    id: 'prod-6',
    name: 'Nestle a+ Greek Yoghurt',
    category: 'Dairy, Bread & Eggs',
    price: 1.99,
    stockQty: 200,
    sku: 'DAIRY-YG-006',
    imageUrl: 'https://picsum.photos/seed/yogurt/200/200',
    imageHint: 'yogurt cup',
    expiryDate: addDays(today, 1),
    mfgDate: subtractDays(addDays(today, 1), 15),
    daysUntilExpiry: 1,
    averageDailySales: 12,
    shopId: 'shop-3',
    description: "Enjoy the thick, creamy texture of Nestle a+ Greek Yoghurt. It's a delicious and healthy snack, packed with protein.",
    nutritionalInfo: { calories: '90kcal', protein: '10g', carbohydrates: '6g', fat: '2g' }
  },
  {
    id: 'prod-7',
    name: 'Amul Butter',
    category: 'Dairy, Bread & Eggs',
    price: 6.5,
    stockQty: 250,
    sku: 'DAIRY-CH-007',
    imageUrl: 'https://picsum.photos/seed/butter/200/200',
    imageHint: 'butter block',
    expiryDate: addDays(today, 45),
    mfgDate: subtractDays(addDays(today, 45), 180),
    daysUntilExpiry: 45,
    averageDailySales: 4,
    shopId: 'shop-1',
    description: "The rich, creamy taste of Amul Butter is perfect for spreading on toast, baking, or cooking your favourite dishes.",
    nutritionalInfo: { calories: '717kcal', protein: '0.9g', carbohydrates: '0.1g', fat: '81g' }
  },
  {
    id: 'prod-44',
    name: 'Amul Cheese Slices',
    category: 'Dairy, Bread & Eggs',
    price: 4.0,
    stockQty: 100,
    sku: 'DAIRY-CS-044',
    imageUrl: 'https://picsum.photos/seed/cheeseslice/200/200',
    imageHint: 'cheese slices',
    expiryDate: addDays(today, 60),
    mfgDate: subtractDays(addDays(today, 60), 90),
    daysUntilExpiry: 60,
    averageDailySales: 20,
    shopId: 'shop-2',
    description: "Perfect for sandwiches and burgers, Amul Cheese Slices are delicious and convenient.",
    nutritionalInfo: { calories: '320kcal', protein: '20g', carbohydrates: '2g', fat: '26g' }
  },
  {
    id: 'prod-45',
    name: 'Mother Dairy Paneer',
    category: 'Dairy, Bread & Eggs',
    price: 3.0,
    stockQty: 200,
    sku: 'DAIRY-PN-045',
    imageUrl: 'https://picsum.photos/seed/paneer/200/200',
    imageHint: 'paneer block',
    expiryDate: addDays(today, 10),
    mfgDate: subtractDays(addDays(today, 10), 5),
    daysUntilExpiry: 10,
    averageDailySales: 15,
    shopId: 'shop-3',
    description: "Fresh and soft, Mother Dairy Paneer is a great source of protein for vegetarian dishes.",
    nutritionalInfo: { calories: '296kcal', protein: '18g', carbohydrates: '4.5g', fat: '22g' }
  },
  {
    id: 'prod-46',
    name: 'Britannia Milk Rusk',
    category: 'Dairy, Bread & Eggs',
    price: 2.0,
    stockQty: 150,
    sku: 'BAKERY-MR-046',
    imageUrl: 'https://picsum.photos/seed/rusk/200/200',
    imageHint: 'rusk biscuit',
    expiryDate: addDays(today, 90),
    mfgDate: subtractDays(addDays(today, 90), 60),
    daysUntilExpiry: 90,
    averageDailySales: 25,
    shopId: 'shop-4',
    description: "Crispy and delicious, Britannia Milk Rusk is the perfect companion for your morning tea.",
    nutritionalInfo: { calories: '445kcal', protein: '9g', carbohydrates: '75g', fat: '12g' }
  },
  {
    id: 'prod-47',
    name: 'Pillsbury Atta',
    category: 'Dairy, Bread & Eggs',
    price: 8.0,
    stockQty: 5000,
    sku: 'GRAIN-AT-047',
    imageUrl: 'https://picsum.photos/seed/atta/200/200',
    imageHint: 'flour bag',
    expiryDate: addDays(today, 120),
    mfgDate: subtractDays(addDays(today, 120), 30),
    daysUntilExpiry: 120,
    averageDailySales: 30,
    shopId: 'shop-1',
    description: "Made from the choicest grains, Pillsbury Atta makes soft and fluffy rotis.",
    nutritionalInfo: { calories: '364kcal', protein: '13g', carbohydrates: '76g', fat: '1.7g' }
  },
  {
    id: 'prod-48',
    name: 'Nestle Milkmaid',
    category: 'Dairy, Bread & Eggs',
    price: 5.5,
    stockQty: 400,
    sku: 'DAIRY-MM-048',
    imageUrl: 'https://picsum.photos/seed/milkmaid/200/200',
    imageHint: 'condensed milk',
    expiryDate: addDays(today, 180),
    mfgDate: subtractDays(addDays(today, 180), 90),
    daysUntilExpiry: 180,
    averageDailySales: 10,
    shopId: 'shop-2',
    description: "Sweet and creamy, Nestle Milkmaid is the perfect ingredient for making delicious desserts.",
    nutritionalInfo: { calories: '321kcal', protein: '8g', carbohydrates: '55g', fat: '8g' }
  },

  // Fruits & Vegetables
  {
    id: 'prod-4',
    name: 'Granny Smith Apples',
    category: 'Fruits & Vegetables',
    price: 2.8,
    stockQty: 1000,
    sku: 'PRODUCE-AP-004',
    imageUrl: 'https://picsum.photos/seed/apple/200/200',
    imageHint: 'green apple',
    expiryDate: addDays(today, 12),
    mfgDate: subtractDays(addDays(today, 12), 7),
    daysUntilExpiry: 12,
    averageDailySales: 20,
    shopId: 'shop-1',
    description: "Crisp and tart, Granny Smith apples are perfect for snacking, baking, and adding a zesty crunch to salads.",
    nutritionalInfo: { calories: '58kcal', protein: '0.4g', carbohydrates: '14g', fat: '0.2g' }
  },
  {
    id: 'prod-8',
    name: 'Organic Bananas',
    category: 'Fruits & Vegetables',
    price: 1.5,
    stockQty: 500,
    sku: 'PRODUCE-BN-008',
    imageUrl: 'https://picsum.photos/seed/banana/200/200',
    imageHint: 'yellow banana',
    expiryDate: addDays(today, 4),
    mfgDate: subtractDays(addDays(today, 4), 6),
    daysUntilExpiry: 4,
    averageDailySales: 25,
    shopId: 'shop-2',
    description: "Our organic bananas are naturally sweet and a great source of potassium. Perfect for a quick energy boost.",
    nutritionalInfo: { calories: '89kcal', protein: '1.1g', carbohydrates: '23g', fat: '0.3g' }
  },
  {
    id: 'prod-11',
    name: 'Fresh Tomatoes',
    category: 'Fruits & Vegetables',
    price: 1.2,
    stockQty: 800,
    sku: 'PRODUCE-TM-011',
    imageUrl: 'https://picsum.photos/seed/tomatoes/200/200',
    imageHint: 'red tomatoes',
    expiryDate: addDays(today, 7),
    mfgDate: subtractDays(addDays(today, 7), 5),
    daysUntilExpiry: 7,
    averageDailySales: 18,
    shopId: 'shop-3',
    description: "Juicy and ripe, these fresh tomatoes are a versatile ingredient for salads, sauces, and sandwiches.",
    nutritionalInfo: { calories: '18kcal', protein: '0.9g', carbohydrates: '3.9g', fat: '0.2g' }
  },
  {
    id: 'prod-12',
    name: 'Local Potatoes',
    category: 'Fruits & Vegetables',
    price: 0.8,
    stockQty: 1500,
    sku: 'PRODUCE-PT-012',
    imageUrl: 'https://picsum.photos/seed/potatoes/200/200',
    imageHint: 'fresh potatoes',
    expiryDate: addDays(today, 30),
    mfgDate: subtractDays(addDays(today, 30), 10),
    daysUntilExpiry: 30,
    averageDailySales: 40,
    shopId: 'shop-4',
    description: "Sourced from local farms, these potatoes are perfect for roasting, mashing, or frying. A kitchen staple.",
    nutritionalInfo: { calories: '77kcal', protein: '2g', carbohydrates: '17g', fat: '0.1g' }
  },
  {
    id: 'prod-13',
    name: 'Fresh Onions',
    category: 'Fruits & Vegetables',
    price: 0.9,
    stockQty: 1200,
    sku: 'PRODUCE-ON-013',
    imageUrl: 'https://picsum.photos/seed/onions/200/200',
    imageHint: 'fresh onions',
    expiryDate: addDays(today, 40),
    mfgDate: subtractDays(addDays(today, 40), 10),
    daysUntilExpiry: 40,
    averageDailySales: 35,
    shopId: 'shop-1',
    description: "Aromatic and flavourful, our fresh onions are an essential ingredient for adding depth to any dish.",
    nutritionalInfo: { calories: '40kcal', protein: '1.1g', carbohydrates: '9.3g', fat: '0.1g' }
  },
  {
    id: 'prod-49',
    name: 'Fresh Carrots',
    category: 'Fruits & Vegetables',
    price: 1.0,
    stockQty: 600,
    sku: 'PRODUCE-CR-049',
    imageUrl: 'https://picsum.photos/seed/carrots/200/200',
    imageHint: 'fresh carrots',
    expiryDate: addDays(today, 14),
    mfgDate: subtractDays(addDays(today, 14), 7),
    daysUntilExpiry: 14,
    averageDailySales: 22,
    shopId: 'shop-2',
    description: "Crunchy and sweet, these fresh carrots are a great source of Vitamin A.",
    nutritionalInfo: { calories: '41kcal', protein: '0.9g', carbohydrates: '10g', fat: '0.2g' }
  },
  {
    id: 'prod-50',
    name: 'Fresh Spinach',
    category: 'Fruits & Vegetables',
    price: 1.5,
    stockQty: 300,
    sku: 'PRODUCE-SP-050',
    imageUrl: 'https://picsum.photos/seed/spinach/200/200',
    imageHint: 'spinach leaves',
    expiryDate: addDays(today, 5),
    mfgDate: subtractDays(addDays(today, 5), 3),
    daysUntilExpiry: 5,
    averageDailySales: 12,
    shopId: 'shop-3',
    description: "Tender and nutritious, fresh spinach is perfect for salads, curries, and smoothies.",
    nutritionalInfo: { calories: '23kcal', protein: '2.9g', carbohydrates: '3.6g', fat: '0.4g' }
  },
  {
    id: 'prod-51',
    name: 'Fresh Cauliflower',
    category: 'Fruits & Vegetables',
    price: 2.0,
    stockQty: 400,
    sku: 'PRODUCE-CF-051',
    imageUrl: 'https://picsum.photos/seed/cauliflower/200/200',
    imageHint: 'cauliflower head',
    expiryDate: addDays(today, 8),
    mfgDate: subtractDays(addDays(today, 8), 4),
    daysUntilExpiry: 8,
    averageDailySales: 18,
    shopId: 'shop-4',
    description: "A versatile vegetable, fresh cauliflower can be used in a variety of dishes from curries to roasted snacks.",
    nutritionalInfo: { calories: '25kcal', protein: '1.9g', carbohydrates: '5g', fat: '0.3g' }
  },
  {
    id: 'prod-52',
    name: 'Fresh Lemons',
    category: 'Fruits & Vegetables',
    price: 0.5,
    stockQty: 1000,
    sku: 'PRODUCE-LM-052',
    imageUrl: 'https://picsum.photos/seed/lemons/200/200',
    imageHint: 'yellow lemons',
    expiryDate: addDays(today, 20),
    mfgDate: subtractDays(addDays(today, 20), 10),
    daysUntilExpiry: 20,
    averageDailySales: 50,
    shopId: 'shop-1',
    description: "Add a zesty kick to your food and drinks with our fresh and juicy lemons.",
    nutritionalInfo: { calories: '29kcal', protein: '1.1g', carbohydrates: '9g', fat: '0.3g' }
  },
  {
    id: 'prod-53',
    name: 'Fresh Ginger',
    category: 'Fruits & Vegetables',
    price: 1.8,
    stockQty: 700,
    sku: 'PRODUCE-GG-053',
    imageUrl: 'https://picsum.photos/seed/ginger/200/200',
    imageHint: 'ginger root',
    expiryDate: addDays(today, 25),
    mfgDate: subtractDays(addDays(today, 25), 10),
    daysUntilExpiry: 25,
    averageDailySales: 30,
    shopId: 'shop-2',
    description: "Aromatic and pungent, fresh ginger is a staple in Asian cooking and has numerous health benefits.",
    nutritionalInfo: { calories: '80kcal', protein: '1.8g', carbohydrates: '18g', fat: '0.8g' }
  },

  // Snacks & Munchies
  {
    id: 'prod-9',
    name: 'Lays Classic Potato Chips',
    category: 'Snacks & Munchies',
    price: 2.49,
    stockQty: 150,
    sku: 'SNACKS-PC-009',
    imageUrl: 'https://picsum.photos/seed/chips/200/200',
    imageHint: 'potato chips',
    expiryDate: addDays(today, 90),
    mfgDate: subtractDays(addDays(today, 90), 90),
    daysUntilExpiry: 90,
    averageDailySales: 30,
    shopId: 'shop-3',
    description: "The classic, crispy potato chips you know and love. Perfectly salted and satisfyingly crunchy.",
    nutritionalInfo: { calories: '536kcal', protein: '7g', carbohydrates: '53g', fat: '35g' }
  },
  {
    id: 'prod-14',
    name: 'Kurkure Masala Munch',
    category: 'Snacks & Munchies',
    price: 1.99,
    stockQty: 200,
    sku: 'SNACKS-KM-014',
    imageUrl: 'https://picsum.photos/seed/kurkure/200/200',
    imageHint: 'puffy snacks',
    expiryDate: addDays(today, 80),
    mfgDate: subtractDays(addDays(today, 80), 100),
    daysUntilExpiry: 80,
    averageDailySales: 25,
    shopId: 'shop-4',
    description: "A spicy, crunchy snack with a unique masala flavour. Kurkure is the perfect tea-time companion.",
    nutritionalInfo: { calories: '550kcal', protein: '6.5g', carbohydrates: '55g', fat: '34g' }
  },
  {
    id: 'prod-15',
    name: 'Haldiram\'s Aloo Bhujia',
    category: 'Snacks & Munchies',
    price: 3.99,
    stockQty: 100,
    sku: 'SNACKS-AB-015',
    imageUrl: 'https://picsum.photos/seed/bhujia/200/200',
    imageHint: 'indian snack',
    expiryDate: addDays(today, 120),
    mfgDate: subtractDays(addDays(today, 120), 120),
    daysUntilExpiry: 120,
    averageDailySales: 20,
    shopId: 'shop-1',
    description: "A popular Indian snack made from potato and gram flour. Crispy, spicy, and addictively delicious.",
    nutritionalInfo: { calories: '580kcal', protein: '14g', carbohydrates: '42g', fat: '39g' }
  },
  {
    id: 'prod-16',
    name: 'Britannia Good Day Cookies',
    category: 'Snacks & Munchies',
    price: 2.99,
    stockQty: 180,
    sku: 'SNACKS-GD-016',
    imageUrl: 'https://picsum.photos/seed/goodday/200/200',
    imageHint: 'cashew cookies',
    expiryDate: addDays(today, 150),
    mfgDate: subtractDays(addDays(today, 150), 180),
    daysUntilExpiry: 150,
    averageDailySales: 40,
    shopId: 'shop-2',
    description: "Rich, buttery cookies with a sprinkling of cashews. The perfect way to make any day a Good Day.",
    nutritionalInfo: { calories: '510kcal', protein: '7g', carbohydrates: '68g', fat: '24g' }
  },
  {
    id: 'prod-54',
    name: 'Bingo Mad Angles',
    category: 'Snacks & Munchies',
    price: 1.5,
    stockQty: 250,
    sku: 'SNACKS-MA-054',
    imageUrl: 'https://picsum.photos/seed/madangles/200/200',
    imageHint: 'triangle chips',
    expiryDate: addDays(today, 100),
    mfgDate: subtractDays(addDays(today, 100), 90),
    daysUntilExpiry: 100,
    averageDailySales: 35,
    shopId: 'shop-3',
    description: "Get your snack game on with the unique texture and flavour of Bingo Mad Angles.",
    nutritionalInfo: { calories: '540kcal', protein: '7g', carbohydrates: '60g', fat: '30g' }
  },
  {
    id: 'prod-55',
    name: 'Doritos Nacho Cheese',
    category: 'Snacks & Munchies',
    price: 3.0,
    stockQty: 120,
    sku: 'SNACKS-NC-055',
    imageUrl: 'https://picsum.photos/seed/doritos/200/200',
    imageHint: 'nacho chips',
    expiryDate: addDays(today, 110),
    mfgDate: subtractDays(addDays(today, 110), 100),
    daysUntilExpiry: 110,
    averageDailySales: 28,
    shopId: 'shop-4',
    description: "The bold flavour of nacho cheese in a crunchy tortilla chip. Perfect for parties or a solo snack.",
    nutritionalInfo: { calories: '498kcal', protein: '7.1g', carbohydrates: '55.5g', fat: '27.8g' }
  },
  {
    id: 'prod-56',
    name: 'Pringles Original',
    category: 'Snacks & Munchies',
    price: 4.5,
    stockQty: 90,
    sku: 'SNACKS-PO-056',
    imageUrl: 'https://picsum.photos/seed/pringles/200/200',
    imageHint: 'pringles can',
    expiryDate: addDays(today, 200),
    mfgDate: subtractDays(addDays(today, 200), 180),
    daysUntilExpiry: 200,
    averageDailySales: 15,
    shopId: 'shop-1',
    description: "Once you pop, you can't stop! The original stackable potato crisp.",
    nutritionalInfo: { calories: '520kcal', protein: '5.6g', carbohydrates: '56g', fat: '30g' }
  },
  {
    id: 'prod-57',
    name: 'Too Yumm Karare',
    category: 'Snacks & Munchies',
    price: 1.8,
    stockQty: 220,
    sku: 'SNACKS-YK-057',
    imageUrl: 'https://picsum.photos/seed/tooyumm/200/200',
    imageHint: 'baked snacks',
    expiryDate: addDays(today, 95),
    mfgDate: subtractDays(addDays(today, 95), 90),
    daysUntilExpiry: 95,
    averageDailySales: 32,
    shopId: 'shop-2',
    description: "A healthier, baked snack with a punch of Indian spices. All the taste, none of the guilt.",
    nutritionalInfo: { calories: '450kcal', protein: '8g', carbohydrates: '70g', fat: '15g' }
  },
  {
    id: 'prod-58',
    name: 'Balaji Wafers',
    category: 'Snacks & Munchies',
    price: 1.0,
    stockQty: 300,
    sku: 'SNACKS-BW-058',
    imageUrl: 'https://picsum.photos/seed/balaji/200/200',
    imageHint: 'wafers pack',
    expiryDate: addDays(today, 85),
    mfgDate: subtractDays(addDays(today, 85), 90),
    daysUntilExpiry: 85,
    averageDailySales: 45,
    shopId: 'shop-3',
    description: "Light, crispy, and perfectly salted. A simple yet satisfying potato wafer.",
    nutritionalInfo: { calories: '550kcal', protein: '6g', carbohydrates: '54g', fat: '34g' }
  },
  {
    id: 'prod-59',
    name: 'Yellow Diamond Rings',
    category: 'Snacks & Munchies',
    price: 0.8,
    stockQty: 400,
    sku: 'SNACKS-YD-059',
    imageUrl: 'https://picsum.photos/seed/yellowdiamond/200/200',
    imageHint: 'ring snack',
    expiryDate: addDays(today, 75),
    mfgDate: subtractDays(addDays(today, 75), 90),
    daysUntilExpiry: 75,
    averageDailySales: 50,
    shopId: 'shop-4',
    description: "Fun to eat and full of flavour. These crunchy rings are a favourite among kids.",
    nutritionalInfo: { calories: '530kcal', protein: '7g', carbohydrates: '58g', fat: '30g' }
  },

  // Cold Drinks & Juices
  {
    id: 'prod-10',
    name: 'Coca-Cola Can',
    category: 'Cold Drinks & Juices',
    price: 1.0,
    stockQty: 300,
    sku: 'DRINKS-COLA-010',
    imageUrl: 'https://picsum.photos/seed/cola/200/200',
    imageHint: 'soda can',
    expiryDate: addDays(today, 180),
    mfgDate: subtractDays(addDays(today, 180), 180),
    daysUntilExpiry: 180,
    averageDailySales: 50,
    shopId: 'shop-1',
    description: "The original and refreshing taste of Coca-Cola. Enjoy the classic cola flavour that's loved worldwide.",
    nutritionalInfo: { calories: '42kcal', protein: '0g', carbohydrates: '10.6g', fat: '0g' }
  },
  {
    id: 'prod-17',
    name: 'Tropicana Orange Juice',
    category: 'Cold Drinks & Juices',
    price: 3.5,
    stockQty: 100,
    sku: 'DRINKS-OJ-017',
    imageUrl: 'https://picsum.photos/seed/orangejuice/200/200',
    imageHint: 'juice carton',
    expiryDate: addDays(today, 100),
    mfgDate: subtractDays(addDays(today, 100), 120),
    daysUntilExpiry: 100,
    averageDailySales: 15,
    shopId: 'shop-2',
    description: "Made from 100% pure pressed fruit, Tropicana Orange Juice is a delicious and healthy way to start your day.",
    nutritionalInfo: { calories: '45kcal', protein: '0.5g', carbohydrates: '10g', fat: '0g' }
  },
  {
    id: 'prod-18',
    name: 'Bisleri Mineral Water',
    category: 'Cold Drinks & Juices',
    price: 0.5,
    stockQty: 500,
    sku: 'DRINKS-MW-018',
    imageUrl: 'https://picsum.photos/seed/water/200/200',
    imageHint: 'water bottle',
    expiryDate: addDays(today, 365),
    mfgDate: subtractDays(addDays(today, 365), 30),
    daysUntilExpiry: 365,
    averageDailySales: 100,
    shopId: 'shop-3',
    description: "Pure, safe, and refreshing. Bisleri Mineral Water is your perfect companion for staying hydrated on the go.",
    nutritionalInfo: { calories: '0kcal', protein: '0g', carbohydrates: '0g', fat: '0g' }
  },
  {
    id: 'prod-19',
    name: 'Sprite Lemon-Lime Soda',
    category: 'Cold Drinks & Juices',
    price: 1.0,
    stockQty: 250,
    sku: 'DRINKS-SP-019',
    imageUrl: 'https://picsum.photos/seed/sprite/200/200',
    imageHint: 'soda bottle',
    expiryDate: addDays(today, 180),
    mfgDate: subtractDays(addDays(today, 180), 180),
    daysUntilExpiry: 180,
    averageDailySales: 45,
    shopId: 'shop-4',
    description: "The crisp, clean taste of lemon-lime makes Sprite a refreshing choice to quench your thirst.",
    nutritionalInfo: { calories: '40kcal', protein: '0g', carbohydrates: '9.8g', fat: '0g' }
  },
  {
    id: 'prod-60',
    name: 'Pepsi Can',
    category: 'Cold Drinks & Juices',
    price: 1.0,
    stockQty: 280,
    sku: 'DRINKS-PEP-060',
    imageUrl: 'https://picsum.photos/seed/pepsi/200/200',
    imageHint: 'pepsi can',
    expiryDate: addDays(today, 170),
    mfgDate: subtractDays(addDays(today, 170), 180),
    daysUntilExpiry: 170,
    averageDailySales: 48,
    shopId: 'shop-1',
    description: "The bold, refreshing taste of Pepsi. Live for now!",
    nutritionalInfo: { calories: '41kcal', protein: '0g', carbohydrates: '10.9g', fat: '0g' }
  },
  {
    id: 'prod-61',
    name: 'Thums Up Can',
    category: 'Cold Drinks & Juices',
    price: 1.1,
    stockQty: 260,
    sku: 'DRINKS-TU-061',
    imageUrl: 'https://picsum.photos/seed/thumsup/200/200',
    imageHint: 'black soda',
    expiryDate: addDays(today, 175),
    mfgDate: subtractDays(addDays(today, 175), 180),
    daysUntilExpiry: 175,
    averageDailySales: 42,
    shopId: 'shop-2',
    description: "Taste the thunder with Thums Up's strong, fizzy and unique flavour.",
    nutritionalInfo: { calories: '40kcal', protein: '0g', carbohydrates: '10g', fat: '0g' }
  },
  {
    id: 'prod-62',
    name: 'Real Fruit Juice - Mixed',
    category: 'Cold Drinks & Juices',
    price: 3.8,
    stockQty: 90,
    sku: 'DRINKS-RF-062',
    imageUrl: 'https://picsum.photos/seed/realjuice/200/200',
    imageHint: 'juice box',
    expiryDate: addDays(today, 110),
    mfgDate: subtractDays(addDays(today, 110), 120),
    daysUntilExpiry: 110,
    averageDailySales: 18,
    shopId: 'shop-3',
    description: "A delicious blend of various fruits, packed with vitamins and minerals.",
    nutritionalInfo: { calories: '50kcal', protein: '0.4g', carbohydrates: '12g', fat: '0g' }
  },
  {
    id: 'prod-63',
    name: 'Amul Lassi',
    category: 'Cold Drinks & Juices',
    price: 1.5,
    stockQty: 150,
    sku: 'DRINKS-AL-063',
    imageUrl: 'https://picsum.photos/seed/lassi/200/200',
    imageHint: 'yogurt drink',
    expiryDate: addDays(today, 15),
    mfgDate: subtractDays(addDays(today, 15), 10),
    daysUntilExpiry: 15,
    averageDailySales: 25,
    shopId: 'shop-4',
    description: "A refreshing and healthy yogurt-based drink. Perfect for cooling down on a hot day.",
    nutritionalInfo: { calories: '75kcal', protein: '2.5g', carbohydrates: '12g', fat: '2g' }
  },
  {
    id: 'prod-64',
    name: 'Red Bull Energy Drink',
    category: 'Cold Drinks & Juices',
    price: 4.0,
    stockQty: 70,
    sku: 'DRINKS-RB-064',
    imageUrl: 'https://picsum.photos/seed/redbull/200/200',
    imageHint: 'energy drink',
    expiryDate: addDays(today, 240),
    mfgDate: subtractDays(addDays(today, 240), 180),
    daysUntilExpiry: 240,
    averageDailySales: 10,
    shopId: 'shop-1',
    description: "Red Bull gives you wings. The classic energy drink for when you need a boost.",
    nutritionalInfo: { calories: '46kcal', protein: '0g', carbohydrates: '11g', fat: '0g' }
  },
  {
    id: 'prod-65',
    name: 'Paper Boat Aamras',
    category: 'Cold Drinks & Juices',
    price: 2.0,
    stockQty: 180,
    sku: 'DRINKS-PB-065',
    imageUrl: 'https://picsum.photos/seed/paperboat/200/200',
    imageHint: 'drink pouch',
    expiryDate: addDays(today, 120),
    mfgDate: subtractDays(addDays(today, 120), 90),
    daysUntilExpiry: 120,
    averageDailySales: 30,
    shopId: 'shop-2',
    description: "A taste of childhood memories. The delicious and authentic flavour of mangoes in a drink.",
    nutritionalInfo: { calories: '60kcal', protein: '0.1g', carbohydrates: '15g', fat: '0g' }
  },
  
  // Breakfast & Instant Food
  {
    id: 'prod-24',
    name: 'Maggi 2-Minute Noodles',
    category: 'Breakfast & Instant Food',
    price: 0.5,
    stockQty: 400,
    sku: 'INST-MG-024',
    imageUrl: 'https://picsum.photos/seed/maggi/200/200',
    imageHint: 'instant noodles',
    expiryDate: addDays(today, 270),
    mfgDate: subtractDays(addDays(today, 270), 90),
    daysUntilExpiry: 270,
    averageDailySales: 60,
    shopId: 'shop-3',
    description: "India's favourite instant noodles. Ready in just 2 minutes, Maggi is perfect for a quick and satisfying meal.",
    nutritionalInfo: { calories: '427kcal', protein: '8g', carbohydrates: '63.5g', fat: '15.7g' }
  },
  {
    id: 'prod-25',
    name: 'Quaker Oats',
    category: 'Breakfast & Instant Food',
    price: 4.0,
    stockQty: 80,
    sku: 'INST-QO-025',
    imageUrl: 'https://picsum.photos/seed/oats/200/200',
    imageHint: 'oats box',
    expiryDate: addDays(today, 300),
    mfgDate: subtractDays(addDays(today, 300), 180),
    daysUntilExpiry: 300,
    averageDailySales: 10,
    shopId: 'shop-4',
    description: "Start your day with a healthy bowl of Quaker Oats. It's a great source of fibre and helps manage weight.",
    nutritionalInfo: { calories: '389kcal', protein: '16.9g', carbohydrates: '66.3g', fat: '6.9g' }
  },
  {
    id: 'prod-26',
    name: 'Kellogg\'s Corn Flakes',
    category: 'Breakfast & Instant Food',
    price: 5.0,
    stockQty: 100,
    sku: 'INST-CF-026',
    imageUrl: 'https://picsum.photos/seed/cornflakes/200/200',
    imageHint: 'cereal box',
    expiryDate: addDays(today, 320),
    mfgDate: subtractDays(addDays(today, 320), 180),
    daysUntilExpiry: 320,
    averageDailySales: 15,
    shopId: 'shop-1',
    description: "A classic breakfast cereal, Kellogg's Corn Flakes are toasted to perfection for a crispy, crunchy start to your day.",
    nutritionalInfo: { calories: '378kcal', protein: '7.5g', carbohydrates: '84.1g', fat: '0.4g' }
  },
  {
    id: 'prod-27',
    name: 'MTR Poha Mix',
    category: 'Breakfast & Instant Food',
    price: 2.5,
    stockQty: 120,
    sku: 'INST-PH-027',
    imageUrl: 'https://picsum.photos/seed/poha/200/200',
    imageHint: 'instant poha',
    expiryDate: addDays(today, 180),
    mfgDate: subtractDays(addDays(today, 180), 120),
    daysUntilExpiry: 180,
    averageDailySales: 20,
    shopId: 'shop-2',
    description: "A delicious and convenient way to enjoy the traditional Indian breakfast of Poha. Ready in minutes.",
    nutritionalInfo: { calories: '350kcal', protein: '8g', carbohydrates: '75g', fat: '2g' }
  },
  {
    id: 'prod-66',
    name: 'Saffola Masala Oats',
    category: 'Breakfast & Instant Food',
    price: 3.0,
    stockQty: 110,
    sku: 'INST-SO-066',
    imageUrl: 'https://picsum.photos/seed/masalaoats/200/200',
    imageHint: 'masala oats',
    expiryDate: addDays(today, 200),
    mfgDate: subtractDays(addDays(today, 200), 150),
    daysUntilExpiry: 200,
    averageDailySales: 18,
    shopId: 'shop-3',
    description: "A tasty and healthy twist to your regular oats. A savoury snack that's ready in minutes.",
    nutritionalInfo: { calories: '380kcal', protein: '12g', carbohydrates: '65g', fat: '8g' }
  },
  {
    id: 'prod-67',
    name: 'Kissan Peanut Butter',
    category: 'Breakfast & Instant Food',
    price: 6.0,
    stockQty: 70,
    sku: 'INST-PB-067',
    imageUrl: 'https://picsum.photos/seed/peanutbutter/200/200',
    imageHint: 'peanut butter',
    expiryDate: addDays(today, 240),
    mfgDate: subtractDays(addDays(today, 240), 180),
    daysUntilExpiry: 240,
    averageDailySales: 10,
    shopId: 'shop-4',
    description: "Creamy and delicious, Kissan Peanut Butter is a great source of protein for your breakfast.",
    nutritionalInfo: { calories: '588kcal', protein: '25g', carbohydrates: '20g', fat: '50g' }
  },
  {
    id: 'prod-68',
    name: 'ID Fresho Idli/Dosa Batter',
    category: 'Breakfast & Instant Food',
    price: 4.0,
    stockQty: 50,
    sku: 'INST-ID-068',
    imageUrl: 'https://picsum.photos/seed/batter/200/200',
    imageHint: 'batter pack',
    expiryDate: addDays(today, 7),
    mfgDate: subtractDays(addDays(today, 7), 3),
    daysUntilExpiry: 7,
    averageDailySales: 25,
    shopId: 'shop-1',
    description: "Make fresh and fluffy idlis and dosas at home with this ready-to-use batter.",
    nutritionalInfo: { calories: '140kcal', protein: '5g', carbohydrates: '28g', fat: '0.5g' }
  },
  {
    id: 'prod-69',
    name: 'Kellogg\'s Chocos',
    category: 'Breakfast & Instant Food',
    price: 5.5,
    stockQty: 90,
    sku: 'INST-CH-069',
    imageUrl: 'https://picsum.photos/seed/chocos/200/200',
    imageHint: 'chocolate cereal',
    expiryDate: addDays(today, 310),
    mfgDate: subtractDays(addDays(today, 310), 180),
    daysUntilExpiry: 310,
    averageDailySales: 16,
    shopId: 'shop-2',
    description: "A chocolaty breakfast cereal that kids love. A fun and tasty start to the day.",
    nutritionalInfo: { calories: '390kcal', protein: '8g', carbohydrates: '80g', fat: '4g' }
  },
  {
    id: 'prod-70',
    name: 'Top Ramen Instant Noodles',
    category: 'Breakfast & Instant Food',
    price: 0.6,
    stockQty: 350,
    sku: 'INST-TR-070',
    imageUrl: 'https://picsum.photos/seed/topramen/200/200',
    imageHint: 'ramen noodles',
    expiryDate: addDays(today, 260),
    mfgDate: subtractDays(addDays(today, 260), 90),
    daysUntilExpiry: 260,
    averageDailySales: 55,
    shopId: 'shop-3',
    description: "Another popular choice for instant noodles, Top Ramen offers a variety of flavours.",
    nutritionalInfo: { calories: '430kcal', protein: '9g', carbohydrates: '62g', fat: '16g' }
  },
  {
    id: 'prod-71',
    name: 'Kissan Mixed Fruit Jam',
    category: 'Breakfast & Instant Food',
    price: 4.5,
    stockQty: 130,
    sku: 'INST-JF-071',
    imageUrl: 'https://picsum.photos/seed/jam/200/200',
    imageHint: 'jam jar',
    expiryDate: addDays(today, 300),
    mfgDate: subtractDays(addDays(today, 300), 180),
    daysUntilExpiry: 300,
    averageDailySales: 14,
    shopId: 'shop-4',
    description: "A delicious blend of various fruits. Perfect for spreading on toast and bread.",
    nutritionalInfo: { calories: '270kcal', protein: '0.2g', carbohydrates: '68g', fat: '0.1g' }
  },
  
  // Sweet Tooth
  {
    id: 'prod-28',
    name: 'Cadbury Dairy Milk',
    category: 'Sweet Tooth',
    price: 1.0,
    stockQty: 500,
    sku: 'SWEET-DM-028',
    imageUrl: 'https://picsum.photos/seed/dairymilk/200/200',
    imageHint: 'chocolate bar',
    expiryDate: addDays(today, 240),
    mfgDate: subtractDays(addDays(today, 240), 120),
    daysUntilExpiry: 240,
    averageDailySales: 80,
    shopId: 'shop-1',
    description: "The classic, creamy taste of Cadbury Dairy Milk chocolate, made with a glass and a half of full cream milk.",
    nutritionalInfo: { calories: '535kcal', protein: '7.3g', carbohydrates: '59.5g', fat: '30.5g' }
  },
  {
    id: 'prod-29',
    name: 'Amul Ice Cream (Vanilla)',
    category: 'Sweet Tooth',
    price: 3.0,
    stockQty: 60,
    sku: 'SWEET-IC-029',
    imageUrl: 'https://picsum.photos/seed/icecream/200/200',
    imageHint: 'ice cream tub',
    expiryDate: addDays(today, 90),
    mfgDate: subtractDays(addDays(today, 90), 60),
    daysUntilExpiry: 90,
    averageDailySales: 8,
    shopId: 'shop-2',
    description: "Rich and creamy, Amul's Vanilla ice cream is the perfect treat to satisfy your sweet cravings.",
    nutritionalInfo: { calories: '207kcal', protein: '3.5g', carbohydrates: '22.8g', fat: '11g' }
  },
  {
    id: 'prod-32',
    name: 'Haldiram\'s Gulab Jamun',
    category: 'Sweet Tooth',
    price: 5.0,
    stockQty: 70,
    sku: 'SWEET-GJ-032',
    imageUrl: 'https://picsum.photos/seed/gulabjamun/200/200',
    imageHint: 'indian sweets',
    expiryDate: addDays(today, 150),
    mfgDate: subtractDays(addDays(today, 150), 90),
    daysUntilExpiry: 150,
    averageDailySales: 10,
    shopId: 'shop-3',
    description: "Soft, spongy, and soaked in sweet syrup, Haldiram's Gulab Jamun is a classic Indian dessert.",
    nutritionalInfo: { calories: '300kcal', protein: '4g', carbohydrates: '45g', fat: '12g' }
  },
    {
    id: 'prod-33',
    name: 'Kisses Chocolate',
    category: 'Sweet Tooth',
    price: 4.0,
    stockQty: 100,
    sku: 'SWEET-KC-033',
    imageUrl: 'https://picsum.photos/seed/kisses/200/200',
    imageHint: 'small chocolates',
    expiryDate: addDays(today, 260),
    mfgDate: subtractDays(addDays(today, 260), 180),
    daysUntilExpiry: 260,
    averageDailySales: 25,
    shopId: 'shop-4',
    description: "Individually wrapped, bite-sized milk chocolates. Perfect for sharing or a personal treat.",
    nutritionalInfo: { calories: '230kcal', protein: '3g', carbohydrates: '25g', fat: '13g' }
  },
  {
    id: 'prod-72',
    name: 'Cadbury 5 Star',
    category: 'Sweet Tooth',
    price: 0.8,
    stockQty: 600,
    sku: 'SWEET-5S-072',
    imageUrl: 'https://picsum.photos/seed/5star/200/200',
    imageHint: 'caramel chocolate',
    expiryDate: addDays(today, 230),
    mfgDate: subtractDays(addDays(today, 230), 120),
    daysUntilExpiry: 230,
    averageDailySales: 90,
    shopId: 'shop-1',
    description: "The classic combination of chocolate, caramel, and nougat. Get lost in the rich and chewy taste.",
    nutritionalInfo: { calories: '450kcal', protein: '4g', carbohydrates: '65g', fat: '20g' }
  },
  {
    id: 'prod-73',
    name: 'Nestle KitKat',
    category: 'Sweet Tooth',
    price: 1.2,
    stockQty: 450,
    sku: 'SWEET-KK-073',
    imageUrl: 'https://picsum.photos/seed/kitkat/200/200',
    imageHint: 'wafer chocolate',
    expiryDate: addDays(today, 250),
    mfgDate: subtractDays(addDays(today, 250), 120),
    daysUntilExpiry: 250,
    averageDailySales: 85,
    shopId: 'shop-2',
    description: "Have a break, have a KitKat. The iconic chocolate-covered wafer bar.",
    nutritionalInfo: { calories: '520kcal', protein: '6g', carbohydrates: '65g', fat: '27g' }
  },
  {
    id: 'prod-74',
    name: 'Parle Melody',
    category: 'Sweet Tooth',
    price: 0.2,
    stockQty: 1000,
    sku: 'SWEET-ML-074',
    imageUrl: 'https://picsum.photos/seed/melody/200/200',
    imageHint: 'chocolate candy',
    expiryDate: addDays(today, 365),
    mfgDate: subtractDays(addDays(today, 365), 180),
    daysUntilExpiry: 365,
    averageDailySales: 200,
    shopId: 'shop-3',
    description: "A classic chocolaty toffee that's loved by all. Melody itni chocolaty kyun hai?",
    nutritionalInfo: { calories: '400kcal', protein: '2g', carbohydrates: '80g', fat: '8g' }
  },
  {
    id: 'prod-75',
    name: 'Alpenliebe Juzt Jelly',
    category: 'Sweet Tooth',
    price: 1.0,
    stockQty: 300,
    sku: 'SWEET-JJ-075',
    imageUrl: 'https://picsum.photos/seed/jelly/200/200',
    imageHint: 'fruit jelly',
    expiryDate: addDays(today, 200),
    mfgDate: subtractDays(addDays(today, 200), 120),
    daysUntilExpiry: 200,
    averageDailySales: 60,
    shopId: 'shop-4',
    description: "Fun and fruity jelly candies that are a delight to eat.",
    nutritionalInfo: { calories: '330kcal', protein: '0g', carbohydrates: '82g', fat: '0g' }
  },
  {
    id: 'prod-76',
    name: 'Center Fresh Chewing Gum',
    category: 'Sweet Tooth',
    price: 0.1,
    stockQty: 2000,
    sku: 'SWEET-CF-076',
    imageUrl: 'https://picsum.photos/seed/centerfresh/200/200',
    imageHint: 'chewing gum',
    expiryDate: addDays(today, 400),
    mfgDate: subtractDays(addDays(today, 400), 180),
    daysUntilExpiry: 400,
    averageDailySales: 300,
    shopId: 'shop-1',
    description: "The refreshing chewing gum that gives you a burst of freshness.",
    nutritionalInfo: { calories: '10kcal', protein: '0g', carbohydrates: '2g', fat: '0g' }
  },
  {
    id: 'prod-77',
    name: 'Kwality Wall\'s Cornetto',
    category: 'Sweet Tooth',
    price: 2.5,
    stockQty: 100,
    sku: 'SWEET-CRN-077',
    imageUrl: 'https://picsum.photos/seed/cornetto/200/200',
    imageHint: 'ice cream cone',
    expiryDate: addDays(today, 100),
    mfgDate: subtractDays(addDays(today, 100), 60),
    daysUntilExpiry: 100,
    averageDailySales: 20,
    shopId: 'shop-2',
    description: "The classic ice cream cone with a crunchy cone and a delicious chocolate tip.",
    nutritionalInfo: { calories: '250kcal', protein: '4g', carbohydrates: '30g', fat: '13g' }
  },

  // Bakery & Biscuits
  {
    id: 'prod-30',
    name: 'Parle-G Biscuits',
    category: 'Bakery & Biscuits',
    price: 0.5,
    stockQty: 1000,
    sku: 'BAKE-PG-030',
    imageUrl: 'https://picsum.photos/seed/parleg/200/200',
    imageHint: 'biscuit pack',
    expiryDate: addDays(today, 200),
    mfgDate: subtractDays(addDays(today, 200), 120),
    daysUntilExpiry: 200,
    averageDailySales: 150,
    shopId: 'shop-3',
    description: "The iconic glucose biscuit that's been a favourite for generations. Perfect for dipping in tea or coffee.",
    nutritionalInfo: { calories: '451kcal', protein: '6.5g', carbohydrates: '78g', fat: '13g' }
  },
  {
    id: 'prod-31',
    name: 'Oreo Cookies',
    category: 'Bakery & Biscuits',
    price: 2.0,
    stockQty: 300,
    sku: 'BAKE-OR-031',
    imageUrl: 'https://picsum.photos/seed/oreo/200/200',
    imageHint: 'oreo cookies',
    expiryDate: addDays(today, 220),
    mfgDate: subtractDays(addDays(today, 220), 150),
    daysUntilExpiry: 220,
    averageDailySales: 50,
    shopId: 'shop-4',
    description: "The world's favourite cookie. A rich, creme filling sandwiched between two chocolatey wafers.",
    nutritionalInfo: { calories: '479kcal', protein: '4.9g', carbohydrates: '70g', fat: '20g' }
  },
  {
    id: 'prod-42',
    name: 'Sunfeast Dark Fantasy',
    category: 'Bakery & Biscuits',
    price: 3.0,
    stockQty: 250,
    sku: 'BAKE-DF-042',
    imageUrl: 'https://picsum.photos/seed/darkfantasy/200/200',
    imageHint: 'choco biscuit',
    expiryDate: addDays(today, 210),
    mfgDate: subtractDays(addDays(today, 210), 150),
    daysUntilExpiry: 210,
    averageDailySales: 40,
    shopId: 'shop-1',
    description: "An indulgent cookie with a molten chocolate center. A perfect treat for any time of day.",
    nutritionalInfo: { calories: '500kcal', protein: '5g', carbohydrates: '65g', fat: '25g' }
  },
  {
    id: 'prod-43',
    name: 'McVities Digestive Biscuits',
    category: 'Bakery & Biscuits',
    price: 2.5,
    stockQty: 300,
    sku: 'BAKE-MD-043',
    imageUrl: 'https://picsum.photos/seed/digestive/200/200',
    imageHint: 'digestive biscuit',
    expiryDate: addDays(today, 240),
    mfgDate: subtractDays(addDays(today, 240), 180),
    daysUntilExpiry: 240,
    averageDailySales: 35,
    shopId: 'shop-2',
    description: "A wholesome biscuit made with whole wheat. A good source of fibre and a healthy snacking option.",
    nutritionalInfo: { calories: '480kcal', protein: '7g', carbohydrates: '62g', fat: '21g' }
  },
  {
    id: 'prod-78',
    name: 'Britannia Jim Jam',
    category: 'Bakery & Biscuits',
    price: 1.5,
    stockQty: 280,
    sku: 'BAKE-JJ-078',
    imageUrl: 'https://picsum.photos/seed/jimjam/200/200',
    imageHint: 'cream biscuit',
    expiryDate: addDays(today, 190),
    mfgDate: subtractDays(addDays(today, 190), 120),
    daysUntilExpiry: 190,
    averageDailySales: 45,
    shopId: 'shop-3',
    description: "Creamy vanilla sandwiched between two biscuits, topped with a dollop of jam.",
    nutritionalInfo: { calories: '490kcal', protein: '6g', carbohydrates: '75g', fat: '19g' }
  },
  {
    id: 'prod-79',
    name: 'Parle Monaco',
    category: 'Bakery & Biscuits',
    price: 1.0,
    stockQty: 400,
    sku: 'BAKE-MN-079',
    imageUrl: 'https://picsum.photos/seed/monaco/200/200',
    imageHint: 'salty biscuit',
    expiryDate: addDays(today, 180),
    mfgDate: subtractDays(addDays(today, 180), 120),
    daysUntilExpiry: 180,
    averageDailySales: 60,
    shopId: 'shop-4',
    description: "The classic salted biscuit. Light, crispy, and perfect for a savoury snack.",
    nutritionalInfo: { calories: '485kcal', protein: '9g', carbohydrates: '68g', fat: '19g' }
  },
  {
    id: 'prod-80',
    name: 'Sunfeast Bounce',
    category: 'Bakery & Biscuits',
    price: 1.2,
    stockQty: 350,
    sku: 'BAKE-SB-080',
    imageUrl: 'https://picsum.photos/seed/bounce/200/200',
    imageHint: 'orange cream',
    expiryDate: addDays(today, 200),
    mfgDate: subtractDays(addDays(today, 200), 120),
    daysUntilExpiry: 200,
    averageDailySales: 55,
    shopId: 'shop-1',
    description: "Cream-filled biscuits available in a variety of flavours. A fun and tasty treat.",
    nutritionalInfo: { calories: '495kcal', protein: '5g', carbohydrates: '72g', fat: '21g' }
  },
  {
    id: 'prod-81',
    name: 'Unibic Choco Chip Cookies',
    category: 'Bakery & Biscuits',
    price: 3.5,
    stockQty: 200,
    sku: 'BAKE-UC-081',
    imageUrl: 'https://picsum.photos/seed/unibic/200/200',
    imageHint: 'chip cookies',
    expiryDate: addDays(today, 230),
    mfgDate: subtractDays(addDays(today, 230), 150),
    daysUntilExpiry: 230,
    averageDailySales: 30,
    shopId: 'shop-2',
    description: "Loaded with chocolate chips, these cookies are a decadent treat for any cookie lover.",
    nutritionalInfo: { calories: '510kcal', protein: '6g', carbohydrates: '65g', fat: '26g' }
  },
  
  // Tea, Coffee & More
  {
    id: 'prod-34',
    name: 'Taj Mahal Tea',
    category: 'Tea, Coffee & More',
    price: 6.0,
    stockQty: 90,
    sku: 'BEV-TM-034',
    imageUrl: 'https://picsum.photos/seed/tajtea/200/200',
    imageHint: 'tea box',
    expiryDate: addDays(today, 365),
    mfgDate: subtractDays(addDays(today, 365), 180),
    daysUntilExpiry: 365,
    averageDailySales: 5,
    shopId: 'shop-3',
    description: "A premium blend of black tea leaves, known for its rich aroma and flavour. A truly regal tea experience.",
    nutritionalInfo: { calories: '1kcal', protein: '0.1g', carbohydrates: '0.2g', fat: '0g' }
  },
  {
    id: 'prod-35',
    name: 'Nescafe Classic Coffee',
    category: 'Tea, Coffee & More',
    price: 7.0,
    stockQty: 80,
    sku: 'BEV-NC-035',
    imageUrl: 'https://picsum.photos/seed/nescafe/200/200',
    imageHint: 'coffee jar',
    expiryDate: addDays(today, 400),
    mfgDate: subtractDays(addDays(today, 400), 200),
    daysUntilExpiry: 400,
    averageDailySales: 7,
    shopId: 'shop-4',
    description: "Start your day with the unmistakable taste of Nescafe Classic. A rich, full-bodied coffee for any occasion.",
    nutritionalInfo: { calories: '2kcal', protein: '0.1g', carbohydrates: '0.3g', fat: '0g' }
  },
  {
    id: 'prod-36',
    name: 'Bournvita Health Drink',
    category: 'Tea, Coffee & More',
    price: 8.0,
    stockQty: 100,
    sku: 'BEV-BV-036',
    imageUrl: 'https://picsum.photos/seed/bournvita/200/200',
    imageHint: 'health drink',
    expiryDate: addDays(today, 300),
    mfgDate: subtractDays(addDays(today, 300), 180),
    daysUntilExpiry: 300,
    averageDailySales: 12,
    shopId: 'shop-1',
    description: "A malted chocolate drink mix that's packed with vitamins and minerals. Perfect for growing kids and adults.",
    nutritionalInfo: { calories: '397kcal', protein: '7.3g', carbohydrates: '85.5g', fat: '2.5g' }
  },
  {
    id: 'prod-37',
    name: 'Lipton Green Tea',
    category: 'Tea, Coffee & More',
    price: 5.5,
    stockQty: 110,
    sku: 'BEV-GT-037',
    imageUrl: 'https://picsum.photos/seed/greentea/200/200',
    imageHint: 'green tea',
    expiryDate: addDays(today, 330),
    mfgDate: subtractDays(addDays(today, 330), 180),
    daysUntilExpiry: 330,
    averageDailySales: 9,
    shopId: 'shop-2',
    description: "Light and refreshing, Lipton Green Tea is a great way to hydrate and feel good. Zero calories and full of flavour.",
    nutritionalInfo: { calories: '0kcal', protein: '0g', carbohydrates: '0g', fat: '0g' }
  },
  {
    id: 'prod-82',
    name: 'Bru Instant Coffee',
    category: 'Tea, Coffee & More',
    price: 6.5,
    stockQty: 85,
    sku: 'BEV-BI-082',
    imageUrl: 'https://picsum.photos/seed/bru/200/200',
    imageHint: 'coffee powder',
    expiryDate: addDays(today, 400),
    mfgDate: subtractDays(addDays(today, 400), 200),
    daysUntilExpiry: 400,
    averageDailySales: 8,
    shopId: 'shop-3',
    description: "A perfect mix of 70% coffee and 30% chicory. Bru Instant offers a rich and aromatic coffee experience.",
    nutritionalInfo: { calories: '2kcal', protein: '0.1g', carbohydrates: '0.3g', fat: '0g' }
  },
  {
    id: 'prod-83',
    name: 'Tata Tea Gold',
    category: 'Tea, Coffee & More',
    price: 5.8,
    stockQty: 95,
    sku: 'BEV-TTG-083',
    imageUrl: 'https://picsum.photos/seed/tatatea/200/200',
    imageHint: 'tea leaves',
    expiryDate: addDays(today, 360),
    mfgDate: subtractDays(addDays(today, 360), 180),
    daysUntilExpiry: 360,
    averageDailySales: 6,
    shopId: 'shop-4',
    description: "A unique blend of Assam CTC and long leaves. Tata Tea Gold offers a rich taste and an uplifting aroma.",
    nutritionalInfo: { calories: '1kcal', protein: '0.1g', carbohydrates: '0.2g', fat: '0g' }
  },
  {
    id: 'prod-84',
    name: 'Horlicks Health Drink',
    category: 'Tea, Coffee & More',
    price: 7.5,
    stockQty: 105,
    sku: 'BEV-HH-084',
    imageUrl: 'https://picsum.photos/seed/horlicks/200/200',
    imageHint: 'malted drink',
    expiryDate: addDays(today, 310),
    mfgDate: subtractDays(addDays(today, 310), 180),
    daysUntilExpiry: 310,
    averageDailySales: 11,
    shopId: 'shop-1',
    description: "A malted milk hot drink that provides nourishment and supports growth. Clinically proven to make kids taller, stronger, and sharper.",
    nutritionalInfo: { calories: '377kcal', protein: '10g', carbohydrates: '79g', fat: '3g' }
  },
  {
    id: 'prod-85',
    name: 'Complan Nutrition Drink',
    category: 'Tea, Coffee & More',
    price: 8.5,
    stockQty: 95,
    sku: 'BEV-CN-085',
    imageUrl: 'https://picsum.photos/seed/complan/200/200',
    imageHint: 'nutrition powder',
    expiryDate: addDays(today, 320),
    mfgDate: subtractDays(addDays(today, 320), 180),
    daysUntilExpiry: 320,
    averageDailySales: 10,
    shopId: 'shop-2',
    description: "A complete planned food in a drink, Complan provides balanced nutrition for growing children.",
    nutritionalInfo: { calories: '417kcal', protein: '18g', carbohydrates: '58g', fat: '12g' }
  },
  
  // Masala, Oil & More
  {
    id: 'prod-38',
    name: 'Everest Turmeric Powder',
    category: 'Masala, Oil & More',
    price: 2.0,
    stockQty: 200,
    sku: 'MASALA-TP-038',
    imageUrl: 'https://picsum.photos/seed/turmeric/200/200',
    imageHint: 'spice powder',
    expiryDate: addDays(today, 365),
    mfgDate: subtractDays(addDays(today, 365), 180),
    daysUntilExpiry: 365,
    averageDailySales: 15,
    shopId: 'shop-3',
    description: "Made from the finest quality turmeric, this powder adds a vibrant yellow colour and a warm, earthy flavour to your dishes.",
    nutritionalInfo: { calories: '354kcal', protein: '8g', carbohydrates: '65g', fat: '10g' }
  },
  {
    id: 'prod-39',
    name: 'Saffola Gold Edible Oil',
    category: 'Masala, Oil & More',
    price: 10.0,
    stockQty: 100,
    sku: 'MASALA-EO-039',
    imageUrl: 'https://picsum.photos/seed/oil/200/200',
    imageHint: 'oil bottle',
    expiryDate: addDays(today, 240),
    mfgDate: subtractDays(addDays(today, 240), 180),
    daysUntilExpiry: 240,
    averageDailySales: 8,
    shopId: 'shop-4',
    description: "A healthy blend of rice bran oil and corn oil, Saffola Gold is designed to help keep your family's heart healthy.",
    nutritionalInfo: { calories: '900kcal', protein: '0g', carbohydrates: '0g', fat: '100g' }
  },
  {
    id: 'prod-40',
    name: 'Tata Salt',
    category: 'Masala, Oil & More',
    price: 1.0,
    stockQty: 1000,
    sku: 'MASALA-TS-040',
    imageUrl: 'https://picsum.photos/seed/salt/200/200',
    imageHint: 'salt pack',
    expiryDate: addDays(today, 730),
    mfgDate: subtractDays(addDays(today, 730), 180),
    daysUntilExpiry: 730,
    averageDailySales: 50,
    shopId: 'shop-1',
    description: "India's first iodized salt brand. Tata Salt provides the right amount of iodine to support mental development.",
    nutritionalInfo: { calories: '0kcal', protein: '0g', carbohydrates: '0g', fat: '0g' }
  },
  {
    id: 'prod-41',
    name: 'MDH Garam Masala',
    category: 'Masala, Oil & More',
    price: 3.0,
    stockQty: 150,
    sku: 'MASALA-GM-041',
    imageUrl: 'https://picsum.photos/seed/garammasala/200/200',
    imageHint: 'masala box',
    expiryDate: addDays(today, 300),
    mfgDate: subtractDays(addDays(today, 300), 180),
    daysUntilExpiry: 300,
    averageDailySales: 12,
    shopId: 'shop-2',
    description: "A rich blend of aromatic spices, MDH Garam Masala adds warmth and depth to a variety of Indian dishes.",
    nutritionalInfo: { calories: '400kcal', protein: '10g', carbohydrates: '50g', fat: '18g' }
  },
  {
    id: 'prod-86',
    name: 'Aashirvaad Atta',
    category: 'Masala, Oil & More',
    price: 9.0,
    stockQty: 400,
    sku: 'MASALA-AA-086',
    imageUrl: 'https://picsum.photos/seed/aashirvaad/200/200',
    imageHint: 'atta bag',
    expiryDate: addDays(today, 120),
    mfgDate: subtractDays(addDays(today, 120), 30),
    daysUntilExpiry: 120,
    averageDailySales: 25,
    shopId: 'shop-3',
    description: "Made from the choicest grains, Aashirvaad Atta makes soft and fluffy rotis.",
    nutritionalInfo: { calories: '364kcal', protein: '13g', carbohydrates: '76g', fat: '1.7g' }
  },
  {
    id: 'prod-87',
    name: 'Fortune Sunlite Refined Sunflower Oil',
    category: 'Masala, Oil & More',
    price: 9.5,
    stockQty: 120,
    sku: 'MASALA-FS-087',
    imageUrl: 'https://picsum.photos/seed/fortuneoil/200/200',
    imageHint: 'oil pouch',
    expiryDate: addDays(today, 250),
    mfgDate: subtractDays(addDays(today, 250), 180),
    daysUntilExpiry: 250,
    averageDailySales: 9,
    shopId: 'shop-4',
    description: "A light and healthy cooking oil, Fortune Sunlite is rich in Vitamin E and is perfect for everyday cooking.",
    nutritionalInfo: { calories: '900kcal', protein: '0g', carbohydrates: '0g', fat: '100g' }
  },
  {
    id: 'prod-88',
    name: 'Everest Red Chilli Powder',
    category: 'Masala, Oil & More',
    price: 2.5,
    stockQty: 180,
    sku: 'MASALA-RCP-088',
    imageUrl: 'https://picsum.photos/seed/chillipowder/200/200',
    imageHint: 'red powder',
    expiryDate: addDays(today, 350),
    mfgDate: subtractDays(addDays(today, 350), 180),
    daysUntilExpiry: 350,
    averageDailySales: 18,
    shopId: 'shop-1',
    description: "Add a spicy kick to your dishes with Everest Red Chilli Powder. Made from high-quality red chillies.",
    nutritionalInfo: { calories: '282kcal', protein: '12g', carbohydrates: '56g', fat: '14g' }
  },
  {
    id: 'prod-89',
    name: 'Catch Coriander Powder',
    category: 'Masala, Oil & More',
    price: 2.2,
    stockQty: 190,
    sku: 'MASALA-CP-089',
    imageUrl: 'https://picsum.photos/seed/coriander/200/200',
    imageHint: 'brown powder',
    expiryDate: addDays(today, 340),
    mfgDate: subtractDays(addDays(today, 340), 180),
    daysUntilExpiry: 340,
    averageDailySales: 16,
    shopId: 'shop-2',
    description: "Adds a fresh and aromatic flavour to your curries and vegetable dishes.",
    nutritionalInfo: { calories: '298kcal', protein: '12g', carbohydrates: '55g', fat: '18g' }
  },
  {
    id: 'prod-90',
    name: 'Maggi Magic Cubes (Veg)',
    category: 'Masala, Oil & More',
    price: 1.5,
    stockQty: 300,
    sku: 'MASALA-MMC-090',
    imageUrl: 'https://picsum.photos/seed/magiccubes/200/200',
    imageHint: 'bouillon cubes',
    expiryDate: addDays(today, 280),
    mfgDate: subtractDays(addDays(today, 280), 150),
    daysUntilExpiry: 280,
    averageDailySales: 25,
    shopId: 'shop-3',
    description: "Enhance the flavour of your everyday vegetarian dishes with these magic cubes.",
    nutritionalInfo: { calories: '250kcal', protein: '5g', carbohydrates: '30g', fat: '12g' }
  },
  {
    id: 'prod-91',
    name: 'Daawat Basmati Rice',
    category: 'Masala, Oil & More',
    price: 12.0,
    stockQty: 200,
    sku: 'MASALA-DBR-091',
    imageUrl: 'https://picsum.photos/seed/basmatirice/200/200',
    imageHint: 'rice bag',
    expiryDate: addDays(today, 700),
    mfgDate: subtractDays(addDays(today, 700), 365),
    daysUntilExpiry: 700,
    averageDailySales: 10,
    shopId: 'shop-4',
    description: "Long-grain and aromatic, Daawat Basmati Rice is the perfect choice for making delicious biryanis and pulaos.",
    nutritionalInfo: { calories: '350kcal', protein: '8g', carbohydrates: '78g', fat: '0.5g' }
  },
  // Kala Store Products
  {
    id: 'prod-kala-1',
    name: 'Fresh Tomatoes',
    category: 'Fruits & Vegetables',
    categoryId: 'cat-3',
    price: 2.5,
    unit: '1kg',
    stockQty: 100,
    sku: 'KALA-TOM-001',
    imageUrl: 'https://picsum.photos/seed/tomatoes/200/200',
    imageHint: 'fresh tomatoes',
    expiryDate: addDays(today, 5),
    mfgDate: subtractDays(today, 1),
    daysUntilExpiry: 5,
    averageDailySales: 15,
    shopId: 'shop-kala',
    description: "Fresh, locally sourced tomatoes perfect for cooking and salads.",
    inStock: true,
    nutritionalInfo: { calories: '18kcal', protein: '0.9g', carbohydrates: '3.9g', fat: '0.2g' }
  },
  {
    id: 'prod-kala-2',
    name: 'Organic Spinach',
    category: 'Fruits & Vegetables',
    categoryId: 'cat-3',
    price: 3.0,
    unit: '500g',
    stockQty: 80,
    sku: 'KALA-SPI-002',
    imageUrl: 'https://picsum.photos/seed/spinach/200/200',
    imageHint: 'fresh spinach',
    expiryDate: addDays(today, 3),
    mfgDate: subtractDays(today, 1),
    daysUntilExpiry: 3,
    averageDailySales: 12,
    shopId: 'shop-kala',
    description: "Fresh organic spinach leaves, rich in iron and vitamins.",
    inStock: true,
    nutritionalInfo: { calories: '23kcal', protein: '2.9g', carbohydrates: '3.6g', fat: '0.4g' }
  },
  {
    id: 'prod-kala-3',
    name: 'Premium Basmati Rice',
    category: 'Masala, Oil & More',
    categoryId: 'cat-10',
    price: 15.0,
    unit: '1kg',
    stockQty: 50,
    sku: 'KALA-RIC-003',
    imageUrl: 'https://picsum.photos/seed/premium-rice/200/200',
    imageHint: 'premium rice',
    expiryDate: addDays(today, 365),
    mfgDate: subtractDays(today, 30),
    daysUntilExpiry: 365,
    averageDailySales: 8,
    shopId: 'shop-kala',
    description: "Premium quality basmati rice with long grains and aromatic fragrance.",
    inStock: true,
    nutritionalInfo: { calories: '350kcal', protein: '8g', carbohydrates: '78g', fat: '0.5g' }
  },
  {
    id: 'prod-kala-4',
    name: 'Fresh Milk',
    category: 'Dairy, Bread & Eggs',
    categoryId: 'cat-2',
    price: 4.0,
    unit: '1L',
    stockQty: 60,
    sku: 'KALA-MIL-004',
    imageUrl: 'https://picsum.photos/seed/fresh-milk/200/200',
    imageHint: 'fresh milk',
    expiryDate: addDays(today, 2),
    mfgDate: subtractDays(today, 1),
    daysUntilExpiry: 2,
    averageDailySales: 20,
    shopId: 'shop-kala',
    description: "Fresh, pure milk delivered daily from local farms.",
    inStock: true,
    nutritionalInfo: { calories: '60kcal', protein: '3.5g', carbohydrates: '4.5g', fat: '3.1g' }
  },
  {
    id: 'prod-kala-5',
    name: 'Whole Wheat Bread',
    category: 'Dairy, Bread & Eggs',
    categoryId: 'cat-2',
    price: 2.0,
    unit: '1 loaf',
    stockQty: 40,
    sku: 'KALA-BRE-005',
    imageUrl: 'https://picsum.photos/seed/wheat-bread/200/200',
    imageHint: 'wheat bread',
    expiryDate: addDays(today, 4),
    mfgDate: subtractDays(today, 1),
    daysUntilExpiry: 4,
    averageDailySales: 10,
    shopId: 'shop-kala',
    description: "Freshly baked whole wheat bread, perfect for healthy breakfast.",
    inStock: true,
    nutritionalInfo: { calories: '247kcal', protein: '13g', carbohydrates: '41g', fat: '4.2g' }
  },
];

export const mockComplaints: Complaint[] = [
  {
    id: 'complaint-1',
    customerId: 'customer-1',
    customerName: 'Rajesh Kumar',
    customerEmail: 'rajesh.kumar@email.com',
    shopId: 'shop-1',
    shopName: 'Kiran General Store',
    productId: 'prod-1',
    productName: 'Amul Taaza Toned Milk',
    orderId: 'order-1',
    type: 'product_quality',
    priority: 'high',
    status: 'pending',
    subject: 'Expired Milk Product',
    description: 'I received expired milk from this shop. The expiry date was yesterday but the product was still being sold.',
    evidence: {
      images: ['https://picsum.photos/seed/expired-milk/400/300'],
      documents: []
    },
    submittedAt: new Date('2024-03-15T10:30:00Z'),
    followUpRequired: true,
    followUpDate: new Date('2024-03-20T10:30:00Z')
  },
  {
    id: 'complaint-2',
    customerId: 'customer-2',
    customerName: 'Priya Sharma',
    customerEmail: 'priya.sharma@email.com',
    shopId: 'shop-2',
    shopName: 'Reliance Fresh',
    orderId: 'order-2',
    type: 'service_issue',
    priority: 'medium',
    status: 'under_review',
    subject: 'Rude Behavior by Shop Staff',
    description: 'The shop staff was very rude and unhelpful when I asked about product availability.',
    submittedAt: new Date('2024-03-14T15:45:00Z'),
    reviewedAt: new Date('2024-03-15T09:00:00Z'),
    reviewedBy: 'admin-1',
    adminNotes: 'Customer service training required for staff'
  },
  {
    id: 'complaint-3',
    customerId: 'customer-3',
    customerName: 'Amit Patel',
    customerEmail: 'amit.patel@email.com',
    shopId: 'shop-3',
    shopName: 'Sharma Provision Store',
    productId: 'prod-8',
    productName: 'Organic Bananas',
    orderId: 'order-3',
    type: 'hygiene',
    priority: 'urgent',
    status: 'resolved',
    subject: 'Unhygienic Storage of Fruits',
    description: 'The fruits are stored in unhygienic conditions with flies around them.',
    evidence: {
      images: ['https://picsum.photos/seed/unhygienic-fruits/400/300'],
      documents: []
    },
    submittedAt: new Date('2024-03-10T12:20:00Z'),
    reviewedAt: new Date('2024-03-11T08:30:00Z'),
    reviewedBy: 'admin-2',
    resolution: 'Shop owner has been warned and hygiene standards have been improved. Regular inspections scheduled.',
    resolutionDate: new Date('2024-03-12T16:00:00Z'),
    adminNotes: 'Hygiene inspection completed. Shop meets standards now.',
    customerSatisfaction: 'satisfied'
  },
  {
    id: 'complaint-4',
    customerId: 'customer-4',
    customerName: 'Sunita Reddy',
    customerEmail: 'sunita.reddy@email.com',
    shopId: 'shop-4',
    shopName: 'Big Bazaar',
    productId: 'prod-16',
    productName: 'Britannia Good Day Cookies',
    orderId: 'order-4',
    type: 'pricing',
    priority: 'low',
    status: 'rejected',
    subject: 'Overcharging on Products',
    description: 'The shop is charging more than the MRP mentioned on the product packaging.',
    submittedAt: new Date('2024-03-12T14:15:00Z'),
    reviewedAt: new Date('2024-03-13T10:00:00Z'),
    reviewedBy: 'admin-1',
    resolution: 'Investigation found that pricing was correct. MRP was properly displayed.',
    resolutionDate: new Date('2024-03-13T10:00:00Z'),
    adminNotes: 'No pricing discrepancy found. Customer may have misread the price.',
    customerSatisfaction: 'dissatisfied'
  },
  {
    id: 'complaint-5',
    customerId: 'customer-5',
    customerName: 'Vikram Singh',
    customerEmail: 'vikram.singh@email.com',
    shopId: 'shop-1',
    shopName: 'Kiran General Store',
    orderId: 'order-5',
    type: 'delivery',
    priority: 'medium',
    status: 'escalated',
    subject: 'Late Delivery and Damaged Items',
    description: 'Order was delivered 2 hours late and some items were damaged during transit.',
    evidence: {
      images: ['https://picsum.photos/seed/damaged-items/400/300'],
      documents: []
    },
    submittedAt: new Date('2024-03-13T18:30:00Z'),
    reviewedAt: new Date('2024-03-14T09:00:00Z'),
    reviewedBy: 'admin-2',
    adminNotes: 'Escalated to delivery partner for investigation. Compensation provided to customer.',
    followUpRequired: true,
    followUpDate: new Date('2024-03-18T09:00:00Z')
  }
];

